웹사이트 업데이트
devdjangokr/dev-django-korea-2018 pull request #24
Opened 2018-09-10 02:30 UTC by Leop0ld

- 장소 추가 & 다음 지도 API 앱 추가 및 그에 따른 appKey 변경
- 시간표 업데이트

2018-09-10 02:31 UTC, raccoonyy commented
캡처화면 볼 수 있을까요? ^^

2018-09-10 03:33 UTC, Leop0ld commented
아직 시간표의 제목이 길어졌을 떄 처리와 모바일의 처리가 되지 않은 상태입니다

2018-09-10 04:26 UTC, raccoonyy approved these changes

2018-09-10 04:26 UTC, raccoonyy commented on index.html
> +                  <div class="col-m-7 col-p-7">파이썬/장고로 API를 뚝딱 만들고, 인프라 스트레스없이 배포하기</div>
`스트레스없이` -> `스트레스 없이`

2018-09-10 04:26 UTC, raccoonyy commented on index.html
> +                    <img src="./src/img/kms.jpg" class="img-responsive"/>
앗! 이건 제가 실수했던 흔적인가보군요! 죄송합니다 ㅠㅠ

2018-09-10 04:33 UTC, Leop0ld commented
@KimWooHyun 우현님 이 부분에서 잘 안되는데 시간날 때 도와주실 수 있으신가요?
![2018-09-10 1 28 09](https://user-images.githubusercontent.com/12431127/45276469-73f59500-b4fd-11e8-8ac1-54c7c9ba8719.png)

col-m-3, col-m-7, col-m-2 를 각각 지정했고, 위의 div 에서는 flex 클래스를 사용하여 3가지 컬럼을 묶고있는 형태입니다. 해당 부분:
https://github.com/devdjangokr/dev-django-korea-2018/pull/24/files#diff-eacf331f0ffc35d4b482f1d15a887d3bR145

이 부분에서 내용이 길어져 여러 줄이 되었을 때, 다음 요소로 넘어가는 현상이 있습니다. 즉, 여러 줄로 표시되지 않고 다음 요소의 공간으로 가버립니다. `overflow` 속성과 연관있을까 싶어 살펴보았으나 제 능력으로는 안되는 부분인 듯 합니다 ㅠㅠ. 모바일에서도 동일한 문제만 수정하면 좋을 것 같은데, 쉽지 않네요.

2018-09-10 06:10 UTC, raccoonyy approved these changes

2018-09-10 12:06 UTC, KimWooHyun commented
@Leop0ld `.session-row`에 `line-height: 100px;` 이 걸려있어서 그런건데, 혹시 넣으신 이유가 있나요? 제플린 시안 상으로는`line-height: normal;` 이네요 > 즉 넣으실 필요 없습니다.

2018-09-10 12:10 UTC, KimWooHyun commented
<img width="976" alt="2018-09-10 9 07 24" src="https://user-images.githubusercontent.com/4816936/45296616-927b8080-b53d-11e8-9702-e8680049591f.png">
보면 `border-radius` 부분이 안맞는것 같아요!

2018-09-10 12:16 UTC, KimWooHyun requested changes

2018-09-10 12:16 UTC, KimWooHyun commented on index.html
> +          <!-- <a class="btn-primary" href="https://goo.gl/forms/XiniTr6gueonFkwq2">스피커 신청</a> -->
주석보다는 이제 티켓신청하기 버튼을 넣고 disabled 하면 어떨까요?

2018-09-10 12:16 UTC, KimWooHyun commented on index.html
> +                <div class="col-m-3 col-p-3 text-center">9:00 ~ 10:10</div>
한시간의 등록은 너무 길 것 같은데 다른분들 의견을 듣고싶어요!
정말 9시부터 오신분들은 1시간을 기다려야 할텐데 너무 긴 시간이지 않을까요?
인원도 그리 많지 않으니 30분 정도 어떨까 생각합니다.

2018-09-10 12:16 UTC, KimWooHyun commented on index.html
> +                <div class="col-m-7 col-p-7">개회식 Keynote</div>
wording은 단순하게 `키노트` 어떤가요 혹은 `Keynote`

2018-09-10 12:16 UTC, KimWooHyun commented on index.html
> +                <div class="session-row flex col-m-12 col-p-12">
마무리 뭐 할게 있을까요?

2018-09-10 12:16 UTC, KimWooHyun commented on index.html
> +  <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=6ce6fd3be99b6b9c2abba7b8873a7346"></script>
앱키가 바뀌었네용?

2018-09-10 12:16 UTC, KimWooHyun commented on src/css/session.css
>  }
EOL

2018-09-11 00:05 UTC, Leop0ld commented on index.html
> +  <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=6ce6fd3be99b6b9c2abba7b8873a7346"></script>
네 제가 공식 이메일로 카카오 개발자 등록하고 앱 만든 뒤에 해당 appKey로 교체했어요

2018-09-11 00:05 UTC, Leop0ld commented on index.html
> +                <div class="col-m-7 col-p-7">개회식 Keynote</div>
`키노트` 로 가겠습니다

2018-09-11 00:06 UTC, Leop0ld commented on index.html
> +                <div class="col-m-3 col-p-3 text-center">9:00 ~ 10:10</div>
저희 후원 제안서에 있는 시간표대로 맞춘거긴 합니다. 애초에 그 쪽에서도 약간 시간 계산이 잘못 되었는지 점심시간도 1시간 20분으로 붕 뜨더라구요. 이 부분은 다시 논의가 필요해보입니다.

2018-09-11 00:07 UTC, Leop0ld commented on index.html
> +          <!-- <a class="btn-primary" href="https://goo.gl/forms/XiniTr6gueonFkwq2">스피커 신청</a> -->
티켓 신청 링크가 없어서 일단 주석 처리해뒀습니다.

2018-09-11 00:08 UTC, Leop0ld commented
https://github.com/devdjangokr/dev-django-korea-2018/pull/24#issuecomment-419890448
이거는 제플린 디자인상 그렇게 보입니다. 애초에 row 하나하나 radius가 있는 게 아니라 그 테이블 전체에 radius가 있는 형태라서 그렇게 했습니다.

2018-09-11 00:12 UTC, Leop0ld commented
https://github.com/devdjangokr/dev-django-korea-2018/pull/24#issuecomment-419889457
그렇게 될 경우, `session-row`에서 `vertical-align` 속성이 먹지 않아서 넣어놨습니다. `line-height` 값을 제거하면 여러 줄로 보이지만 `vertical-align` 속성이 먹지 않네요. 혹시 해결 방법 알고 계신가요?

2018-09-11 00:13 UTC, Leop0ld commented on index.html
> +                <div class="session-row flex col-m-12 col-p-12">
이것 역시 후원 제안서 기준으로 작성되었고, 6시 정각까지 저희가 치우고 나와야하기 때문에 10분 정도 남겨뒀던 걸로 기억합니다.

2018-09-11 01:36 UTC, KimWooHyun commented on index.html
> +                <div class="session-row flex col-m-12 col-p-12">
마무리는 안넣어도 되지 않을까해요. 저때 저희가 할 수 있는 거라던가, 상품 추천이 없는 이상?

2018-09-11 01:36 UTC, KimWooHyun commented on index.html
> +                <div class="col-m-3 col-p-3 text-center">9:00 ~ 10:10</div>
요거는 이번 회의때 아젠다 발의 하지요!

2018-09-11 01:38 UTC, Leop0ld commented on index.html
> +                <div class="session-row flex col-m-12 col-p-12">
6시로 끝나는 것이 깔끔해서 일단 그렇게 해뒀는데 그러면 일단 주석 처리해둘게요.

2018-09-11 01:39 UTC, KimWooHyun commented
제플린 시안 캡쳐:
<img width="91" alt="2018-09-11 10 37 57" src="https://user-images.githubusercontent.com/4816936/45332989-c478fb00-b5ae-11e8-9e87-db127801f2a0.png">

PR 캡쳐:
<img width="110" alt="2018-09-11 10 37 45" src="https://user-images.githubusercontent.com/4816936/45332999-cfcc2680-b5ae-11e8-819f-133f0d6e6474.png">

제가 봤을땐 border 가 2px 로 가서 radius가 붕뜨는 현상이 나타나는 것 같아요

2018-09-11 01:41 UTC, KimWooHyun commented
`line-height` 을 `normal` 이나 `initial` 로 해도 안먹나요?
사실 저는 `div` 안에 글이 있는 경우는 `p` 태그로 감싸거나 `div` 대신 `p`태그를 씁니다.
그리고 `vertical-align` 보다 `flex` 로 처리하거나 `padding`을 줍니다

2018-09-11 01:47 UTC, raccoonyy commented on index.html
> +                <div class="session-row flex col-m-12 col-p-12">
그냥 `끝났어요~`라고 이야기하고, `고생하신 스태프들께 박수 부탁합니다` 정도의 마무리는 어떠세요?

2018-09-11 01:48 UTC, raccoonyy commented on src/css/session.css
>  }
EOF랑 EOL이랑 어떻게 다른가요?

2018-09-11 02:04 UTC, Leop0ld commented
말씀주신대로 `padding`을 이용해서 처리했습니다. border-radius 부분도 8px로 조정하면서 확인했습니다.

2018-09-11 02:05 UTC, KimWooHyun approved these changes

2018-09-11 02:05 UTC, KimWooHyun commented
🚀

2018-09-11 02:06 UTC, Leop0ld commented
OPEN!

2018-09-11 02:06 UTC, merged